
services:
  postgres_nlw:
    container_name: postgres_nlw
    image: postgres 
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: pg_nlw